//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оказанные_услуги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Оказанные_услуги()
        {
            this.Работа_анализатора = new HashSet<Работа_анализатора>();
        }
    
        public int Код_оказанной_услуги { get; set; }
        public Nullable<System.DateTime> Дата_оказания_услуги { get; set; }
        public Nullable<int> Код_заказа { get; set; }
        public Nullable<int> Код_сотрудника { get; set; }
        public Nullable<int> Код_анализатора { get; set; }
        public Nullable<int> Код_услуги { get; set; }
        public string Результат { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Услуга Услуга { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Работа_анализатора> Работа_анализатора { get; set; }
    }
}
