//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Оказанные_услуги = new HashSet<Оказанные_услуги>();
        }
    
        public int Код_заказа { get; set; }
        public Nullable<int> Код_услуги { get; set; }
        public Nullable<System.DateTime> Дата_создания_заказа { get; set; }
        public Nullable<int> Код_статуса_заказа { get; set; }
        public Nullable<int> Код_статуса_услуги { get; set; }
        public string Время_выполнения_заказа { get; set; }
        public Nullable<int> Код_пользователя { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Статус_заказа Статус_заказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оказанные_услуги> Оказанные_услуги { get; set; }
    }
}
