//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Страховая_компания
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Страховая_компания()
        {
            this.Дополнительная_информация = new HashSet<Дополнительная_информация>();
        }
    
        public int Код_страховой_компании { get; set; }
        public string Название_компании { get; set; }
        public string Адрес { get; set; }
        public Nullable<long> ИНН { get; set; }
        public Nullable<long> Расчетный_счет { get; set; }
        public Nullable<long> Банковский_идентификационный_номер { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Дополнительная_информация> Дополнительная_информация { get; set; }
    }
}
