//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Счета_страховым_компаниям
    {
        public int Код_счета { get; set; }
        public Nullable<int> Код_заказа { get; set; }
        public Nullable<int> Код_пользователя_оформившего_заказ { get; set; }
        public Nullable<int> Код_пользователя_ответственного_за_заказ { get; set; }
        public Nullable<int> Код_страховой_компании { get; set; }
        public Nullable<decimal> Общая_сумма { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Страховая_компания Страховая_компания { get; set; }
    }
}
